### ISSUE TITLE
MediocreLoader is not working

### ISSUE THREAD

**Issue by Ratismal** [squeaksies/MediocreMapper#18]
I can't seem to get MediocreLoader to work. 

## Steps Taken

1. Launch MediocreMapper
1. Open a song
1. Launch BeatSaber
1. Click "Start in Beat Saber" within MediocreMapper

## Expected result

The song (assumedly) should be opened in BeatSaber.

## Actual result

BeatSaber continues as it was.

## Additional information

The following logs appear in console
```
*** AcceptConnections accepted connection from 127.0.0.1:61238
*** AddClient added client 127.0.0.1:61238
*** FinalizeConnection starting data receiver for 127.0.0.1:61238 (now 1 clients)
Client connected: 127.0.0.1:61238
*** RemoveClient removed client 127.0.0.1:61238
*** DataReceiver client 127.0.0.1:61238 disconnected (now 0 clients active)
Client disconnected: 127.0.0.1:61238
8 disconnected (now 0 clients active)
sy:::0.0:::True:::1.0
Client disconnected: 127.0.0.1:61238
```

Any help would be greatly appreciated. Thank you!

**Comment by squeaksies** [comment]
MediocreLoader no longer supported
