### ISSUE TITLE
Editor needs the ability to translate selected notes along the timeline

### ISSUE THREAD

**Issue by elyobb** [squeaksies/MediocreMapper#21]
It would be great to be able to use a keyboard shortcut to move selected notes forward or backward along the timeline to the level of the current cursor sensitivity

**Comment by elyobb** [comment]
Looking at the original project this is forked from, it looks like this is alt+drag. Sorry about that, this issue can be closed.

**Comment by squeaksies** [comment]
Additionally, selecting notes and using shift+up/down will move things up and down the timeline.
