### ISSUE TITLE
WidgetLoading.uasset language

### ISSUE THREAD

**Issue by dylanmc** [squeaksies/MediocreMapper#23]
A number of the loading messages don't belong in public software.
Inside jokes, inappropriate language, etc.

**Comment by squeaksies** [comment]
I suppose i could make it private software 🤔

**Comment by dylanmc** [comment]
My comment was offered in the spirit of improving the software, which I appreciate a lot.

**Comment by squeaksies** [comment]
I appreciate the thought but frankly, I have no desire to improve the project in that area! Thanks for your input though!
