### ISSUE TITLE
Walls don't move when shift+clicking

### ISSUE THREAD

**Issue by VineBalloon** [squeaksies/MediocreMapper#25]
Title.

Steps to Reproduce:
1. Make a wall
2. Select it
3. Mash shift+arrows

**Comment by SpyceTewan** [comment]
Yes walls are also not affected by Shift + Arrow Keys

**Comment by VineBalloon** [comment]
Whoops I meant to say shift-arrow in the title

**Comment by squeaksies** [comment]
Should work in Mk4Rev1
