### ISSUE TITLE
Copy-pasting can put blocks outside of the map.

### ISSUE THREAD

**Issue by ProfHugo** [squeaksies/MediocreMapper#26]
Copying a group of blocks and pasting it in a place where there's less space than the section would result in blocks ending up outside the map. 

Example (copying a line of blocks and pasting it at the end):
![screenshot](https://user-images.githubusercontent.com/23370942/53867498-da3d0b00-3fa8-11e9-894c-0df93ba92b65.png)

**Comment by squeaksies** [comment]
totally can. dont do it if you don't want to.

**Comment by ProfHugo** [comment]
I understand. I just find it inconvenient that having to cleanup out-of-bound blocks manually from accidentally selecting few too many blocks during copy pasting results in a stray block placed 3 minutes after the end of the map. Is it possible for you to add a button for cleaning up extraneous artifacts such as this?

**Comment by squeaksies** [comment]
probably not, ill consider adding some accidentially intuitive controls for deleting things outside the end of the map though. reason for not wanting to remove it is that placing notes or other objects outside the end of the map is an actively used in maps, and i would rather not completely remove that if we still have mappers using it. 

most likely ill do a ctrl+click selection at the end of the map will select everything after the end.
