### ISSUE TITLE
Add SongLoader's extra features

### ISSUE THREAD

**Issue by SpyceTewan** [squeaksies/MediocreMapper#27]
The Song loader has a bunch of extra map features like custom colors.
[SongLoader GitHub](https://github.com/Kylemc1413/BeatSaberSongLoader#difficulty-json-additional-fields-ie-expertjson--etc)

```json
"_warnings":["Warning1","Warning2","WarningX"],  
"_information":["Thing1","Thing2","ThingX"], 
"_suggestions":["Mod1","Mod2","ModX"],

"_requirements":["Mod1","Mod2","ModX"], 

"_colorLeft":{"r":1, "g":1, "b":1},
"_colorRight":{"r":1, "g":1, "b":1},

"_noteJumpStartBeatOffset":1, 
```

Right now, you have to edit the json directly, but it would be handy to have this in the editor.

**Comment by squeaksies** [comment]
already planned

**Comment by squeaksies** [comment]
implemented
