### ISSUE TITLE
RGB support

### ISSUE THREAD

**Issue by KureKureciCZ** [squeaksies/MediocreMapper#28]
The RGB support is very badly implemented. There are no input fields, just a circle, so you have to guess the color you want. Also, you cant reset the colors to the default ones. I suggest adding HEX value input field and a "Reset" block, that resets the color to the default ones, so it starts to respect the default red and blue.

**Comment by squeaksies** [comment]
RGB is limited as the creator of the mod that makes RGB usable is unreliable. I no longer plan to support it, but won't take it out either.
