### ISSUE TITLE
using different song file for a skill level

### ISSUE THREAD

**Issue by ashauryn** [squeaksies/MediocreMapper#29]
This might not be an issue, might be operator error.  I made a sped-up version of my song and used a different  .ogg file for the ExpertPlus skill level, as well as changing the BPM for that skill level in the map settings.  However, when I load it in BeatSaber, it just plays the normal version of the song when I play my ExpertPlus map.  Why put "song name" in the skill level form if you can't use different files for different skill levels?

**Comment by squeaksies** [comment]
the functionality no longer exists. this was a feature of beat saber until ~june of last year. the formatting of the json files hasn't changed since then, so it hasn't been removed. I'll consider removing it at some point.

**Comment by squeaksies** [comment]
Now resolved in beatmap 2.0
