### ISSUE TITLE
MacOS Build? (no, seriously, hear me out!)

### ISSUE THREAD

**Issue by themostprime** [squeaksies/MediocreMapper#3]
Would it be easy to make a port of this for MacOS? I know the game is obviously not for MacOS, so the game directory wouldn't be reachable, but it seems like the folder structure is easy to replicate.

The reason I want this is so I can map on the go (I only have a Mac laptop) and just load the folder onto my PC when I get home. Unfortunately, I don't have enough drive space on my Mac for a full Bootcamp install...

**Comment by squeaksies** [comment]
I dont have a mac, and am therefore unable to create a mac build.

also im a-social and am not willing to be cooperative. there have been a few efforts to make a mac build, but im not following them closely.

**Comment by tobiaseisenschenk** [comment]
hey @squeaksies thanks for your effort. I use a mac and would be highly interested in a mac build. Is there any way I could contribute a PR?
Unfortunately I couldnt find any other projects who already provide a custom mapper for osx.

**Comment by squeaksies** [comment]
Sorry, not happening. MM has gone closed source from Mk3 Rev2 onwards, and I'm not accepting any help or PRs right now.
