### ISSUE TITLE
Feature Request: adjustable timline

### ISSUE THREAD

**Issue by RedDrumJay** [squeaksies/MediocreMapper#31]
I know you can plug in new bpm for songs now, but that's kind of a pain. It would be nice if there could be a handle you could grab to slide and re-align the time line to sync with the spectrograph and optionally enter a new bpm. 

Also...if there were a way to import the beat finder track from Audacity and key measures off of that....
![time shift](https://user-images.githubusercontent.com/1888234/55430443-be029e80-5553-11e9-979f-92c1ff579e8e.png)

**Comment by squeaksies** [comment]
Not going to happen. Beat saber was very much not built with this kind of functionality in mind and thus doing this would cause huge problems with performance and setting up the song, at least with changing BPM like that. the current usable "workaround" that i use myself is placing a BPM change at the desired point and cut/paste all the notes and events i need to move. but a slider for that kind of functionaloty is completely out of the question for performance reasons.
