### ISSUE TITLE
Feature Request: scrolling audio playback

### ISSUE THREAD

**Issue by RedDrumJay** [squeaksies/MediocreMapper#32]
When you are scrolling back and forth with the mousewheel trying to find that exact point where you want to put a block along the spectrogram, it would be cool if the audio played as you scrolled as well.

**Comment by squeaksies** [comment]
tried to do this previously. Something with UE4's audio playback has a bit of a performance issue when it comes to playing and stopping a song in rapid sucession. Sorry, dont think itll happen.
