### ISSUE TITLE
6 lane mode does not enable

### ISSUE THREAD

**Issue by therandomuser** [squeaksies/MediocreMapper#34]
i cant seem to get 6 lane mapping support on songs (even songs that were mapped using hellmapper). iv looked around and i cant seem to find any extra setting (other than the under beta) that enables it.
Edit: precision rotation doesn't work either.

**Comment by SpyceTewan** [comment]
Can confirm. When enabling 6 lane mode, the preview block _sometimes_ shows up in the right place but doesn't want to get placed
![grafik](https://user-images.githubusercontent.com/31664665/56315658-8bae8f00-6158-11e9-9e58-bdd2e7390613.png)

**Comment by therandomuser** [comment]
a previously 6 lane map does this (the two notes have been force out of their 6 lane position/swapped sides)
![6 lane issues](https://user-images.githubusercontent.com/24213630/56318538-4b2d2200-6114-11e9-963e-4fa73550d82c.png)

**Comment by therandomuser** [comment]
iv solved this issue. you require mapping extensions in your plugins folder, 6 lane mode to be selected, and for 'Mapping Extensions' to be inputted into Requirements.

**Comment by GuusDeKroon** [comment]
Where can you download the plugin? Can't find it anywhere

**Comment by therandomuser** [comment]
describe your issues? are you looking for more lanes in beatsaber? or how
to map with more lans and the like?
