### ISSUE TITLE
Feature request: Custom colors

### ISSUE THREAD

**Issue by SpyceTewan** [squeaksies/MediocreMapper#36]
Already suggested this but was not added: Custom left and right color chooser

**Comment by therandomuser** [comment]
thats called chroma toggle

**Comment by jtmurdo** [comment]
I believe he means a way to select colors to be displayed in the editor, but still have them be assigned to red and blue. Would be useful for those of us who like to invert our colors in Beat Saber.

**Comment by squeaksies** [comment]
absolutely denied. Implementation did exist but it was removed due to my lack of trust in mappers. Implementation may be added back in when i deem the implementation "safe" enough.

**Comment by SpyceTewan** [comment]
No I mean the _colorLeft and _colorRight json attributes you can put into the difficulty file to have custom colors. I'd like to have custom colors in my level but the editor removes these attributes when saving

**Comment by squeaksies** [comment]
yes, that is also what i mean. Custom colors were added then removed before any public build was released. 

Mk4 was kodified to retain fields like that, though I'll not have it availble in editor.
