### ISSUE TITLE
Unable to edit OFFSET , having to do it manually and alter info.json in Custom Songs in Beat Saber.

### ISSUE THREAD

**Issue by LexraxVR** [squeaksies/MediocreMapper#38]
Opened up Mediocre Mapper v4. Made new song , Named It, Chose difficulty, etc. Dragged all required files into Custom Song directory song.ogg, cover.jpeg via Window Desktop.   Clicked SAVE , it saved all info. Went into song to check was correct and noticed OFFSET was wrong , went to input correct OFFSET (eg -0.441) and clicked on APPLY and then  instead of saving the correct offset, it reverted back to 0.0 OFFSET.

My Analasys:

Upon custom song directory inspection i noticed that their was NO Difficulty Level showing , it was just info.json , cover.jpeg , song.ogg and autosave folder. I checked the Autosave folder and difficulty was in their. Maybee incorrect directory saving in Mediocre Mapper v4 ?

**Comment by squeaksies** [comment]
Should have caught this before. Offset is in ms, not seconds, sub millisecond precision on offset is completely overkill. it gets rounded down to 0

**Comment by ChildishGiant** [comment]
This caught me out at first because ArrowVortex gives values in seconds (eg -0.441)
