### ISSUE TITLE
Unmeme button not working: Interface will stay in "meme mode"

### ISSUE THREAD

**Issue by bleutwo** [squeaksies/MediocreMapper#4]
When I click the "Unmeme" button, the interface does not keep the setting.

![2018-11-12_21-13-49](https://user-images.githubusercontent.com/25549100/48372785-fea26e00-e6bf-11e8-8cf0-17e5118334d7.gif)

MediocreMapper version: Mk2Rev1
OS: Windows 10, 1809

**Comment by squeaksies** [comment]
unmeme button clearly states "release to rememe" keep the button held to stay in unmeme mode
