### ISSUE TITLE
Feature request: Swap blue and red

### ISSUE THREAD

**Issue by jtmurdo** [squeaksies/MediocreMapper#41]
I'm used to red being on the right side due to other games, so mapping with blue on the right massively confuses me. It would be nice to have the ability to swap the notes in the editor, but just having a button that switches red to blue in the file, and vice versa, would do.

**Comment by squeaksies** [comment]
nope

**Comment by squeaksies** [comment]
Just kidding maybe actually.

**Comment by jtmurdo** [comment]
you cant do that to me, man :D

**Comment by squeaksies** [comment]
Mirror button in Mk4Rev1 will swap only the colors if shift is held
