### ISSUE TITLE
Spawn Distance Modifier does not save

### ISSUE THREAD

**Issue by SpyceTewan** [squeaksies/MediocreMapper#42]
Every time I load the map, it's being reset to 0.

I checked the json and it turns out that the spawn distance is simply not being saved.
I am using mapping extensions, 6 lanes mode and precision rotation, but same happens to all my maps

**Comment by SpyceTewan** [comment]
After more testing it appears that the value is actually saved into the json but not loaded into the text input field on map load.

**Comment by squeaksies** [comment]
Fixed in Mk4Rev1
