### ISSUE TITLE
Songs don't load up

### ISSUE THREAD

**Issue by theVRperson** [squeaksies/MediocreMapper#46]
the songs will not load up without mediocre loader. I can't get that. My expansions don't fix anything...

https://steamuserimages-a.akamaihd.net/ugc/788604629989923476/839227A09C7188449C23C6DCFE744FBA8A566846/  click to see the problem 👆

**Comment by squeaksies** [comment]
outdated songloader.

**Comment by theVRperson** [comment]
i fixed it it turns out my song browser was broken
