### ISSUE TITLE
Okay this is actually nitpicking

### ISSUE THREAD

**Issue by SpyceTewan** [squeaksies/MediocreMapper#51]
![grafik](https://user-images.githubusercontent.com/31664665/58991788-6bf72700-87e9-11e9-935b-a0a3df487070.png)

**Comment by legoandmars** [comment]
literally unusable

**Comment by SpyceTewan** [comment]
Worst editor ever

**Comment by therandomuser** [comment]
absolutely terrible

**Comment by squeaksies** [comment]
Murdered the text to the right, issue solved. 😎
