### ISSUE TITLE
Opening a map & pressing Esc the first time removes all bookmarks

### ISSUE THREAD

**Issue by AlmostAnthony** [squeaksies/MediocreMapper#52]
Title + if you manually save, exit, and re-open they are permenantly gone.

This has been a bit frustrating since the Mk4 release, as a current project of mine basically requires the indication and jumping to sections with bookmarks. Oddly, I've yet to see this reported as I have experienced this since either the first or second day Mk4 came out.

A fix would be appreciated, thanks for an awesome mapper!

**Comment by AlmostAnthony** [comment]
I'd also like to add that using MMMM after a while of mapping bookmarks dissapear too, as far as I know without doing/pressing anything specific.

**Comment by SpyceTewan** [comment]
I also had all my bookmarks disappear for no reason

**Comment by briman0094** [comment]
This is happening to me as well. I can't figure out how to restore the original functionality of the Esc key after opening a song. I didn't realize at first that my bookmarks got deleted and had to create them all from scratch again.

**Comment by squeaksies** [comment]
Resolved in Mk4Rev1
