### ISSUE TITLE
Feature request: insert notes with keyboard

### ISSUE THREAD

**Issue by ragcsalo** [squeaksies/MediocreMapper#54]
I would like to insert blue and red notes to a default spot (lower lane, center) with default orientation (ie. down) by pressing two different keys, while playing the music. I would edit notes placement and orientation later. Could you add this feature? :-)

**Comment by squeaksies** [comment]
just added it to my WIP build. will be in next version

**Comment by ragcsalo** [comment]
Great, thanks! :-) Waiting for the release... :-)

**Comment by squeaksies** [comment]
the buttons are M and , as of Mk4Rev1, though i forgot to include it in the controls list
