### ISSUE TITLE
Beta modes (mapping extensions) bug and bug fix

### ISSUE THREAD

**Issue by therandomuser** [squeaksies/MediocreMapper#56]
![image](https://user-images.githubusercontent.com/24213630/59961713-424c2a00-9490-11e9-8898-1b5af889cb63.png)
the picture says it all. it wasn't like this before. heck i even mapped a map with precision placement in it. whats even weirder is that mapping extensions is working... even though mapping extensions is not selected... weird

**Comment by therandomuser** [comment]
nvm. just had to reset my directory. i guess this is now a bug.

**Comment by therandomuser** [comment]
you can close the issue @squeaksies but not that this... should probably fixed. or at least but under a troubleshooting tab.

**Comment by therandomuser** [comment]
nope don't close this issue. after resetting my settings, i am no longer able to map 2.0 songs. idk if you even gave mm the functionality to map those maps, but i was able to for a bit

**Comment by squeaksies** [comment]
did you change your directory path to something else? other than the normal beat saber root, or beat saber/custom songs?

**Comment by squeaksies** [comment]
additionally, MM cannot currently map 2.0 songs. the converter used in songcore is non-destructive, so you've been messing with those if you had been mapping them before.

I think i'm understanding now. MM does not support 2.0 songs, and additionally will not support the mapping extension settings if you do not set your songs folder to the root beat saber folder.

This is not a bug, it's a consequence of MM not being up to date with the current format

**Comment by therandomuser** [comment]
what happened was that i had converted the song by accident while it was
being used by the editor. after that, mapping extensions stuff disappeared.
it was really weird because i was still able to map them even after they
had turned into the new format. and yes it was the root folder. it was
super weird.
