### ISSUE TITLE
[REQ] Move camera up/down/left/right holding L+R mouse

### ISSUE THREAD

**Issue by jacob-danell** [squeaksies/MediocreMapper#58]
A lot of 3D software uses L+R mouse button at the same time to move up/down/left/rigth. Adding this into MediocreMapper would help people move around much faster instead of having to fly around to position or use shift and space to position them in a good spot.
L+R mouse also gives you better presission to set the camera where you want it.

Cheers!

**Comment by squeaksies** [comment]
im not quite sure what you mean, nor have i seen this in any software. give me an example of one and i may look into it and see if i can replicate

**Comment by jacob-danell** [comment]
After some checking I got the shortcut wrong, it's not L+R mouse, the holding down middle mouse/scrol wheel to pan the viewer like here: https://youtu.be/PCPyy_RVEhM?t=337

**Comment by squeaksies** [comment]
Middle mouse is a very commonly used keybind in MM, and i'm not really willing to put another commonly used keybind onto it. 

So I'm gonna have to say no for now, and recommend RMB + WASD/shift/space
