### ISSUE TITLE
Feature Request: OCDless Precision Placement

### ISSUE THREAD

**Issue by therandomuser** [squeaksies/MediocreMapper#64]
for precision placement, it would be incredibly nice if i could set the precision, kinda like how i set cursor precision.
this first set of grids would be sorta what i was thinking of, with the notes snapping to the middle of the square. you could only go to a certain point before the grid would become too cluttered but it would look nice.
![grid](https://user-images.githubusercontent.com/24213630/61575215-f59f4300-aa7d-11e9-8442-0485a1737494.jpg)
you could also use dots instead (imagine the dots as transparent and there being no lines) once the grid became too cluttered, or you could use them from the get go.
![grid with dots](https://user-images.githubusercontent.com/24213630/61575214-f59f4300-aa7d-11e9-9ed7-cdd77db23cf4.jpg)

**Comment by squeaksies** [comment]
already been implemented in WIP version for a while. will be released soon
