### ISSUE TITLE
Lightmap will not close

### ISSUE THREAD

**Issue by ButterMilkBoyz** [squeaksies/MediocreMapper#68]
Maybe I'm missing something, but when opening lightmap, via Shift+Tab then clicking "lightmap" there is no way to close the window that pops up. Even after completely exiting thew application and reloading it, the lightmap window is there. Immovable. AM I missing something or is it stuck there?

Thanks

**Comment by squeaksies** [comment]
press the 出口 button. 
there's also a bug currently where pressing the lightmap button multiple times will make multiple stacked windows, and you'll need to close them all.

**Comment by squeaksies** [comment]
Fixed in Mk4Rev1
