### ISSUE TITLE
I'm in the map maker but can't do anything

### ISSUE THREAD

**Issue by MinisterMadness** [squeaksies/MediocreMapper#69]
I'm in the spot you would be able to make the actual map but can't do anything but move around. the menu and everything is gone. so I'm stuck doing nothing. tried to uninstall it and reinstall it but it's still an issue

**Comment by squeaksies** [comment]
Delete C:\Users\[username]\AppData\Local\MediocreMapper and give it another shot. still unsure what causes this. something something corrupt configs.

**Comment by MinisterMadness** [comment]
Yeah, that seemed to be the problem. It works now.

**Comment by therandomuser** [comment]
close this issue that that its fixed @MinisterMadness
