### ISSUE TITLE
Backspace sends you to the start of the track

### ISSUE THREAD

**Issue by DonTrolav** [squeaksies/MediocreMapper#7]
Since the last update, pressing backspace sends you to the start of the track.
In earlier iterations, it would send you to the playback bar.

**Comment by Thynix** [comment]
Meaning this is a change between Mk2 and Mk2Rev1?

**Comment by DonTrolav** [comment]
No, it is a change between version Mk1Rev1 and Mk2.
I didn't see any change notes about that feature, so I wanted to check if that's intentional.

**Comment by squeaksies** [comment]
it was originally a reset for camera position, but it causes the camera to move all the way back to the start due to the performance update. 

I forgot to fix that. I'll get it working properly (hopefully) next update.

**Comment by squeaksies** [comment]
All fixed up now in mk3
