### ISSUE TITLE
What license is this project under?

### ISSUE THREAD

**Issue by Thynix** [squeaksies/MediocreMapper#8]
So, I know this is a fork of a fork, so answering this question might be difficult, but what license is this code under? The relevant portion of the Unreal Engine [End User License Agreement](https://www.unrealengine.com/en-US/eula) is section 1.B.ii:

> You may not combine, Distribute, or otherwise use the Licensed Technology with any code or other content which is covered by a license that would directly or indirectly require that all or part of the Licensed Technology be governed under any terms other than those of this Agreement (“Non-Compatible License”). Code or content under the following licenses, for example, are prohibited: GNU General Public License (GPL), Lesser GPL (LGPL) (unless you are merely dynamically linking a shared library), or Creative Commons Attribution-ShareAlike License. Code or content under the following licenses, for example, are allowed: BSD License, MIT License, Microsoft Public License, or Apache License. You may not sublicense the Licensed Technology under a Non-Compatible License.

So BSD, MIT, or Apache seem good candidates.

**Comment by squeaksies** [comment]
added MIT license! thanks!
